language: node_js
node_js:
    - "0.12"
    - "0.11"
install:
- npm install
services: mongodb
env:
  global:
  - TWILIO_APP_SID: somenotr3al4pps1dgoeshere
  - MONGO_URL: mongodb://localhost/call-tracking
  - secure: BA1Qtq8OGfwEaXSmd20NeNGSUd4miBZe/kChnjBS2PG3JABfRITHPPT3cxwMEiNXpRRrtX+EkzwHQYgiktQBxu7CgzbSFnfmN56Xx5VrztNm6sJ0XzREvJ+fmFLLORsaRNqrRuWdOCW8j6nqr86x9ygsAaUsq1mQeOMg9YaJnlA66wxbfZ+TzHOuluGQgIAyP/HyGeqm3dLg5sNqGsvawdL5R7q5sjlYdrW/v/hjBMakLq5hi4Mf8kdalu839ZH5zPa7UOqND91gXDCAEU44txgZFuLVFrjpevoooil5Hdd+wYd3sd0b308epbcpw4bdkNRjU4h4XVwMQAomoGZQL+jbPfWgN24wk+S9e3Jg64NWOgEqGavGv6umvpzgByVNX6woLV6SDVFzGGhTmjDoQVbKOFKL+1Te/wOidrCINIQUvyPw60lKYlQgvbgnAgdwLxNxtYRwsDy9WrQOwassng7aaBGo9tLmeohe/P/6e7pBy2f6dfpR8iD9KmTmzFt3z5Z8PMjk+UCs5bNtzqcVcMGT5P9MPJw32p1qymmewuHPiKl6aOmPYAOfn9SUUFMXbvCYt6k5PkYXL4zhHg4rqnJrdMCJIa92jTuU5/YkxN8qMe0YiuFY39LYI8YC10dpKesYGIQ02edBsUVl1e2N6rCu17pQdnPVoBItYrDNvSg=
  - secure: Wghl3SEyTc/7GfzdH2I/8vJignzrhksXXHEP8vSBAR8aZ3c1s9p48LzUoQNeKaMES4ppFkhDiCm/6HFs2W1/AReLuAaEjcAKtHIrZ1xhscgh0HMT5bI6hqXgwpFwyP1+yhAF3u0SH1ZdKOMBjQmW0aA/1I4afeyEH8Hj58a9ElH84zZP6nIpj8KfxEwUqwMhCZZRhh06R87YHT6ZmKy4KjqVedSBUzH/8zD0Z3zFX1VQD5sWfaBE67dDMVW/MFXgQcE7XQqXtIbr7p3EiiqpFqXcxy5wbcNepUClWh1BQJod34sGeFxPXrVIQAsLTZpKO197PdFhjIgXvW9NDQI84QZHMhKucHtG/1GA3LVeu4dnpuEOOMkDln0eHkeZ7Kl5YdwjSGcGiXZom0hAIY+ZpyBud4e/7shpaXJU/1BtqekZQzi6IK6YspPZIaZ5UwJEasZs3etXsqvMcHP6/GfWRk5fTeNZQ8rCReL9KSKtNgHC5iq6O7Z5a7ypx0ZSlkJJXoQdg843LcYt8CGNAD16xucGCEA5luOiPk9PQSz8g4rM+kx3FVeIiVUkwNdJtqKTV6FuqAr63nPM+hriXfY7iQF576PnERRSLlsKThis8t4Nigp6wOouB4ZoTHB4j3iPQM3x6/e6wDWc1nHhAaXo2jWTmfA2ndPP5fpQxpgtVvs=
